/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author ZRI
 */
public class MenuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public MenuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        cardMahasiswa = new javax.swing.JPanel();
        lb_mahasiswa = new javax.swing.JLabel();
        lb_jumlah = new javax.swing.JLabel();
        lb_iconMahasiswa = new javax.swing.JLabel();
        cardDosen = new javax.swing.JPanel();
        lb_dosen = new javax.swing.JLabel();
        lb_jumlah1 = new javax.swing.JLabel();
        lb_iconDosen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cardMahasiswa.setBackground(new java.awt.Color(153, 0, 153));

        lb_mahasiswa.setBackground(new java.awt.Color(153, 153, 153));
        lb_mahasiswa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_mahasiswa.setText("MAHASISWA");

        lb_jumlah.setBackground(new java.awt.Color(153, 153, 153));
        lb_jumlah.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlah.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-student-70.png"))); // NOI18N

        lb_iconMahasiswa.setBackground(new java.awt.Color(153, 153, 153));
        lb_iconMahasiswa.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconMahasiswa.setForeground(new java.awt.Color(0, 102, 153));
        lb_iconMahasiswa.setText("123");

        javax.swing.GroupLayout cardMahasiswaLayout = new javax.swing.GroupLayout(cardMahasiswa);
        cardMahasiswa.setLayout(cardMahasiswaLayout);
        cardMahasiswaLayout.setHorizontalGroup(
            cardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMahasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_mahasiswa)
                .addGap(50, 50, 50)
                .addComponent(lb_jumlah)
                .addGap(20, 20, 20))
            .addGroup(cardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cardMahasiswaLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lb_iconMahasiswa)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        cardMahasiswaLayout.setVerticalGroup(
            cardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardMahasiswaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlah)
                    .addComponent(lb_mahasiswa))
                .addGap(59, 59, 59))
            .addGroup(cardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardMahasiswaLayout.createSequentialGroup()
                    .addContainerGap(90, Short.MAX_VALUE)
                    .addComponent(lb_iconMahasiswa)
                    .addGap(10, 10, 10)))
        );

        cardDosen.setBackground(new java.awt.Color(153, 0, 153));

        lb_dosen.setBackground(new java.awt.Color(153, 153, 153));
        lb_dosen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_dosen.setText("DOSEN");

        lb_jumlah1.setBackground(new java.awt.Color(153, 153, 153));
        lb_jumlah1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlah1.setForeground(new java.awt.Color(0, 102, 153));
        lb_jumlah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-lecturer-69.png"))); // NOI18N

        lb_iconDosen.setBackground(new java.awt.Color(153, 153, 153));
        lb_iconDosen.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_iconDosen.setForeground(new java.awt.Color(0, 102, 153));
        lb_iconDosen.setText("123");

        javax.swing.GroupLayout cardDosenLayout = new javax.swing.GroupLayout(cardDosen);
        cardDosen.setLayout(cardDosenLayout);
        cardDosenLayout.setHorizontalGroup(
            cardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDosenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_dosen)
                .addGap(50, 50, 50)
                .addComponent(lb_jumlah1)
                .addGap(20, 20, 20))
            .addGroup(cardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cardDosenLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(lb_iconDosen)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        cardDosenLayout.setVerticalGroup(
            cardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDosenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlah1)
                    .addComponent(lb_dosen))
                .addGap(59, 59, 59))
            .addGroup(cardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardDosenLayout.createSequentialGroup()
                    .addContainerGap(90, Short.MAX_VALUE)
                    .addComponent(lb_iconDosen)
                    .addGap(10, 10, 10)))
        );

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Master Data > Dashboard");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-dashboard-20.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(cardMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(cardDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(189, 189, 189)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        add(jPanel5, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardDosen;
    private javax.swing.JPanel cardMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_dosen;
    private javax.swing.JLabel lb_iconDosen;
    private javax.swing.JLabel lb_iconMahasiswa;
    private javax.swing.JLabel lb_jumlah;
    private javax.swing.JLabel lb_jumlah1;
    private javax.swing.JLabel lb_mahasiswa;
    // End of variables declaration//GEN-END:variables
}
