
import View.MenuBeribadah;
import View.MenuBersihbersih;
import View.MenuDashboard;
import View.MenuLiburan;
import View.MenuOlahraga;
import View.MenuPekerjaan;
import View.MenuStudying;
import View.MenuTugas;
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ZRI
 */
public class MenuUtama extends javax.swing.JFrame {

    int xx, xy;
    
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pn_Dashboard = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        pn_Studying = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_studying = new javax.swing.JLabel();
        pn_Beribadah = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_beribadah = new javax.swing.JLabel();
        pn_Pekerjaan = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_pekerjaan = new javax.swing.JLabel();
        pn_Tugas = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_tugas = new javax.swing.JLabel();
        pn_Liburan = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_liburan = new javax.swing.JLabel();
        pn_Bersihbersih = new javax.swing.JPanel();
        pn_line6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_bersihbersih = new javax.swing.JLabel();
        pn_Olahraga = new javax.swing.JPanel();
        pn_line7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_olahraga = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_atas = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("JADWALKU");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-schedule-20.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("MASTER DATA");

        pn_Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        pn_line.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-dashboard-20.png"))); // NOI18N

        btn_dashboard.setBackground(new java.awt.Color(102, 102, 102));
        btn_dashboard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_DashboardLayout = new javax.swing.GroupLayout(pn_Dashboard);
        pn_Dashboard.setLayout(pn_DashboardLayout);
        pn_DashboardLayout.setHorizontalGroup(
            pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_DashboardLayout.setVerticalGroup(
            pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DashboardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_dashboard)
                    .addComponent(jLabel4))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_DashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Studying.setBackground(new java.awt.Color(255, 255, 255));

        pn_line1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-studying-30.png"))); // NOI18N

        btn_studying.setBackground(new java.awt.Color(102, 102, 102));
        btn_studying.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_studying.setText("STUDYING");
        btn_studying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_studyingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_studyingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_studyingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_StudyingLayout = new javax.swing.GroupLayout(pn_Studying);
        pn_Studying.setLayout(pn_StudyingLayout);
        pn_StudyingLayout.setHorizontalGroup(
            pn_StudyingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_StudyingLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(btn_studying, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pn_StudyingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_StudyingLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_StudyingLayout.setVerticalGroup(
            pn_StudyingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_StudyingLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_StudyingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_studying)
                    .addComponent(jLabel5))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_StudyingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_StudyingLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Beribadah.setBackground(new java.awt.Color(255, 255, 255));

        pn_line2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-pray-30.png"))); // NOI18N

        btn_beribadah.setBackground(new java.awt.Color(102, 102, 102));
        btn_beribadah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_beribadah.setText("BERIBADAH");
        btn_beribadah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_beribadahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_beribadahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_beribadahMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_BeribadahLayout = new javax.swing.GroupLayout(pn_Beribadah);
        pn_Beribadah.setLayout(pn_BeribadahLayout);
        pn_BeribadahLayout.setHorizontalGroup(
            pn_BeribadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_BeribadahLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(13, 13, 13)
                .addComponent(btn_beribadah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_BeribadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_BeribadahLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(167, Short.MAX_VALUE)))
        );
        pn_BeribadahLayout.setVerticalGroup(
            pn_BeribadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_BeribadahLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_BeribadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_beribadah)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_BeribadahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_BeribadahLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Pekerjaan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-work-30.png"))); // NOI18N

        btn_pekerjaan.setBackground(new java.awt.Color(102, 102, 102));
        btn_pekerjaan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_pekerjaan.setText("PEKERJAAN");
        btn_pekerjaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pekerjaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pekerjaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pekerjaanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_PekerjaanLayout = new javax.swing.GroupLayout(pn_Pekerjaan);
        pn_Pekerjaan.setLayout(pn_PekerjaanLayout);
        pn_PekerjaanLayout.setHorizontalGroup(
            pn_PekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_PekerjaanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_pekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_PekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_PekerjaanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_PekerjaanLayout.setVerticalGroup(
            pn_PekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_PekerjaanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_PekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_pekerjaan)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_PekerjaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_PekerjaanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Tugas.setBackground(new java.awt.Color(255, 255, 255));

        pn_line4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-task-30.png"))); // NOI18N

        btn_tugas.setBackground(new java.awt.Color(102, 102, 102));
        btn_tugas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_tugas.setText("TUGAS");
        btn_tugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tugasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tugasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tugasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_TugasLayout = new javax.swing.GroupLayout(pn_Tugas);
        pn_Tugas.setLayout(pn_TugasLayout);
        pn_TugasLayout.setHorizontalGroup(
            pn_TugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TugasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tugas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pn_TugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_TugasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_TugasLayout.setVerticalGroup(
            pn_TugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TugasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_TugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_tugas)
                    .addComponent(jLabel8))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_TugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_TugasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Liburan.setBackground(new java.awt.Color(255, 255, 255));

        pn_line5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-holiday-30.png"))); // NOI18N

        btn_liburan.setBackground(new java.awt.Color(102, 102, 102));
        btn_liburan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_liburan.setText("LIBURAN");
        btn_liburan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_liburanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_liburanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_liburanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_LiburanLayout = new javax.swing.GroupLayout(pn_Liburan);
        pn_Liburan.setLayout(pn_LiburanLayout);
        pn_LiburanLayout.setHorizontalGroup(
            pn_LiburanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LiburanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(13, 13, 13)
                .addComponent(btn_liburan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(pn_LiburanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_LiburanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_LiburanLayout.setVerticalGroup(
            pn_LiburanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LiburanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_LiburanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_liburan)
                    .addComponent(jLabel9))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_LiburanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_LiburanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Bersihbersih.setBackground(new java.awt.Color(255, 255, 255));
        pn_Bersihbersih.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pn_BersihbersihMouseWheelMoved(evt);
            }
        });

        pn_line6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line6Layout = new javax.swing.GroupLayout(pn_line6);
        pn_line6.setLayout(pn_line6Layout);
        pn_line6Layout.setHorizontalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line6Layout.setVerticalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-cover-up-30.png"))); // NOI18N

        btn_bersihbersih.setBackground(new java.awt.Color(102, 102, 102));
        btn_bersihbersih.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_bersihbersih.setText("BERSIH-BERSIH");
        btn_bersihbersih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_bersihbersihMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bersihbersihMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bersihbersihMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_BersihbersihLayout = new javax.swing.GroupLayout(pn_Bersihbersih);
        pn_Bersihbersih.setLayout(pn_BersihbersihLayout);
        pn_BersihbersihLayout.setHorizontalGroup(
            pn_BersihbersihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_BersihbersihLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bersihbersih)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_BersihbersihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_BersihbersihLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_BersihbersihLayout.setVerticalGroup(
            pn_BersihbersihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_BersihbersihLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_BersihbersihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_bersihbersih)
                    .addComponent(jLabel10))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_BersihbersihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_BersihbersihLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pn_Olahraga.setBackground(new java.awt.Color(255, 255, 255));

        pn_line7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line7Layout = new javax.swing.GroupLayout(pn_line7);
        pn_line7.setLayout(pn_line7Layout);
        pn_line7Layout.setHorizontalGroup(
            pn_line7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pn_line7Layout.setVerticalGroup(
            pn_line7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image1/icons8-sport-30.png"))); // NOI18N

        btn_olahraga.setBackground(new java.awt.Color(102, 102, 102));
        btn_olahraga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_olahraga.setText("OLAHRAGA");
        btn_olahraga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_olahragaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_olahragaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_olahragaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_OlahragaLayout = new javax.swing.GroupLayout(pn_Olahraga);
        pn_Olahraga.setLayout(pn_OlahragaLayout);
        pn_OlahragaLayout.setHorizontalGroup(
            pn_OlahragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_OlahragaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(13, 13, 13)
                .addComponent(btn_olahraga)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(pn_OlahragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_OlahragaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );
        pn_OlahragaLayout.setVerticalGroup(
            pn_OlahragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_OlahragaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_OlahragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_olahraga)
                    .addComponent(jLabel11))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(pn_OlahragaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_OlahragaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_line7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Studying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Tugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Liburan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Bersihbersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Olahraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pn_Beribadah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_Pekerjaan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Studying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Beribadah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Tugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Liburan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Bersihbersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Olahraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_atas.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout pn_atasLayout = new javax.swing.GroupLayout(pn_atas);
        pn_atas.setLayout(pn_atasLayout);
        pn_atasLayout.setHorizontalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1133, Short.MAX_VALUE)
        );
        pn_atasLayout.setVerticalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_atas, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(250, 250, 250));

        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        pn_Dashboard.setBackground(new Color(250,250,250));
        pn_line.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        pn_Dashboard.setBackground(new Color(255,255,255));
        pn_line.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        pn_Dashboard.setBackground(new Color(240,240,240));
        pn_line.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
         this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_studyingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studyingMouseClicked
        pn_Studying.setBackground(new Color(240,240,240));
        pn_line1.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuStudying());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_studyingMouseClicked

    private void btn_studyingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studyingMouseEntered
        pn_Studying.setBackground(new Color(250,250,250));
        pn_line1.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_studyingMouseEntered

    private void btn_studyingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studyingMouseExited
        pn_Studying.setBackground(new Color(255,255,255));
        pn_line1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_studyingMouseExited

    private void btn_beribadahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_beribadahMouseClicked
        pn_Beribadah.setBackground(new Color(240,240,240));
        pn_line2.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuBeribadah());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_beribadahMouseClicked

    private void btn_beribadahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_beribadahMouseEntered
        pn_Beribadah.setBackground(new Color(250,250,250));
        pn_line2.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_beribadahMouseEntered

    private void btn_beribadahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_beribadahMouseExited
        pn_Beribadah.setBackground(new Color(255,255,255));
        pn_line2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_beribadahMouseExited

    private void btn_pekerjaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pekerjaanMouseClicked
        pn_Pekerjaan.setBackground(new Color(240,240,240));
        pn_line3.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuPekerjaan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_pekerjaanMouseClicked

    private void btn_pekerjaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pekerjaanMouseEntered
        pn_Pekerjaan.setBackground(new Color(250,250,250));
        pn_line3.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_pekerjaanMouseEntered

    private void btn_pekerjaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pekerjaanMouseExited
        pn_Pekerjaan.setBackground(new Color(255,255,255));
        pn_line3.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_pekerjaanMouseExited

    private void btn_tugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tugasMouseClicked
        pn_Tugas.setBackground(new Color(240,240,240));
        pn_line4.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuTugas());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_tugasMouseClicked

    private void btn_tugasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tugasMouseEntered
        pn_Tugas.setBackground(new Color(250,250,250));
        pn_line4.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_tugasMouseEntered

    private void btn_tugasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tugasMouseExited
        pn_Tugas.setBackground(new Color(255,255,255));
        pn_line4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_tugasMouseExited

    private void btn_liburanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_liburanMouseClicked
        pn_Liburan.setBackground(new Color(240,240,240));
        pn_line5.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuLiburan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_liburanMouseClicked

    private void btn_liburanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_liburanMouseEntered
        pn_Liburan.setBackground(new Color(250,250,250));
        pn_line5.setBackground(new Color(0,102,153));
    }//GEN-LAST:event_btn_liburanMouseEntered

    private void btn_liburanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_liburanMouseExited
        pn_Liburan.setBackground(new Color(255,255,255));
        pn_line5.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_liburanMouseExited

    private void btn_bersihbersihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bersihbersihMouseClicked
        pn_Bersihbersih.setBackground(new Color(240,240,240));
        pn_line6.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuBersihbersih());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_bersihbersihMouseClicked

    private void btn_bersihbersihMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bersihbersihMouseEntered
        pn_Bersihbersih.setBackground(new Color(255,255,255));
        pn_line6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_bersihbersihMouseEntered

    private void btn_bersihbersihMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bersihbersihMouseExited
        pn_Bersihbersih.setBackground(new Color(255,255,255));
        pn_line6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_bersihbersihMouseExited

    private void btn_olahragaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_olahragaMouseClicked
        pn_Olahraga.setBackground(new Color(240,240,240));
        pn_line7.setBackground(new Color(0,102,153));
        
        pn_utama.removeAll();
        pn_utama.add(new MenuOlahraga());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_olahragaMouseClicked

    private void btn_olahragaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_olahragaMouseEntered
        pn_Olahraga.setBackground(new Color(255,255,255));
        pn_line7.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_olahragaMouseEntered

    private void btn_olahragaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_olahragaMouseExited
        pn_Olahraga.setBackground(new Color(255,255,255));
        pn_line7.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_olahragaMouseExited

    private void pn_BersihbersihMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pn_BersihbersihMouseWheelMoved
       
    }//GEN-LAST:event_pn_BersihbersihMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_beribadah;
    private javax.swing.JLabel btn_bersihbersih;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_liburan;
    private javax.swing.JLabel btn_olahraga;
    private javax.swing.JLabel btn_pekerjaan;
    private javax.swing.JLabel btn_studying;
    private javax.swing.JLabel btn_tugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pn_Beribadah;
    private javax.swing.JPanel pn_Bersihbersih;
    private javax.swing.JPanel pn_Dashboard;
    private javax.swing.JPanel pn_Liburan;
    private javax.swing.JPanel pn_Olahraga;
    private javax.swing.JPanel pn_Pekerjaan;
    private javax.swing.JPanel pn_Studying;
    private javax.swing.JPanel pn_Tugas;
    private javax.swing.JPanel pn_atas;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_line6;
    private javax.swing.JPanel pn_line7;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
